<a href="https://colab.research.google.com/github/JoyKarmoker/Python-Codes-ML/blob/master/Loss_or_Cost_Function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30, 0.7, 1, 0, 0.5])

In [6]:
def mae(y_true, y_predicted):
  total_error = 0;
  for yt, yp in zip(y_true, y_predicted):
    total_error = total_error + abs(yt-yp)

  mae = total_error / len(y_true)
  return mae

In [7]:
mae_error = mae(y_true, y_predicted)
print("Mean absolute error: ",mae_error)

Mean absolute error:  0.5


In [8]:
#using numpy
np.abs(y_true-y_predicted)

array([0.7, 0.3, 1. , 0. , 0.5])

In [9]:
np.mean(np.abs(y_true-y_predicted))

0.5

In [10]:
np.sum(np.abs(y_true-y_predicted))

2.5

In [15]:
def mse(y_true, y_predicted):
  total_error = 0;
  for yt, yp in zip(y_true, y_predicted):
    total_error += abs(yt-yp)*abs(yt-yp)
  
  return total_error / len(y_true) 

In [16]:
mse_error  =mse(y_true, y_predicted)
print("Mean square error ", mse_error)

Mean square error  0.366


In [18]:
np.mean(np.power(np.abs(y_true-y_predicted),2))

0.366

In [19]:
epsilon = 1e-15

In [35]:
y_predicted_new = [max(i, epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [36]:
y_predicted_new = [min(i, 1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [37]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [38]:
np.log(y_predicted)

<ipython-input-38-d8d657355a01>:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted)


array([  0.,   0., -inf, -inf,   0.])